
# This file was *autogenerated* from the file rdd_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10)
from pyspark import SparkContext, SparkConf

conf = SparkConf().setAppName("rdd")
sc = SparkContext(conf=conf)

seeds = ['']
distSeeds = sc.parallelize(seeds)

succ = lambda w: [w+'a', w+'b']

#def distSucc(rdd):
    

C = RecursivelyEnumeratedSet(seeds, succ, structure='forest')




it = C.depth_first_search_iterator()
for i in range(_sage_const_10 ):
    print(next(it))




