
# This file was *autogenerated* from the file speed_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10)
# Vitesse map reduce sur count 4^n #

import time

seeds = [_sage_const_0 ]
succ = lambda x: [x+_sage_const_1 ,x+_sage_const_1 ,x+_sage_const_1 ,x+_sage_const_1 ] if x <= _sage_const_10  else []
S = RecursivelyEnumeratedSet(seeds, succ, structure='forest')

map_function = lambda x: _sage_const_1  if x == _sage_const_10  else _sage_const_0  
reduce_function = lambda x,y: x+y
reduce_init = _sage_const_0 


t1 = time.time()
    
count = S.map_reduce(map_function, reduce_function, reduce_init)

t2 = time.time()


print(count)
print(t2 - t1)

